# Generated by Django 5.1.3 on 2025-02-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pytest', '0002_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='info',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
