# Generated by Django 5.1.3 on 2025-02-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pytest', '0003_service_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='info',
            new_name='github_url',
        ),
        migrations.RemoveField(
            model_name='service',
            name='link',
        ),
        migrations.AddField(
            model_name='service',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
