# Generated by Django 5.1.3 on 2025-02-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pytest', '0004_rename_info_service_github_url_remove_service_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
