# Generated by Django 5.1.3 on 2025-02-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pytest', '0006_user_is_deleted_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='github_url',
            field=models.URLField(blank=True, default='#', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='url',
            field=models.CharField(blank=True, default='#', max_length=200, null=True),
        ),
    ]
