# Generated by Django 5.1.3 on 2025-02-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pytest', '0009_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
