# Generated by Django 5.1.3 on 2025-02-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pytest', '0010_alter_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='media/service_images'),
        ),
    ]
