# Generated by Django 5.1.3 on 2025-02-21 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pytest', '0014_alter_user_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlphaBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.TextField()),
            ],
            options={
                'db_table': 'AlphaBet',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField()),
                ('type', models.TextField()),
                ('description', models.TextField()),
                ('id_alphabet', models.ForeignKey(db_column='ID_ALPHABET', on_delete=django.db.models.deletion.CASCADE, to='pytest.alphabet')),
            ],
            options={
                'db_table': 'Word',
            },
        ),
    ]
