# Generated by Django 5.1.3 on 2025-02-21 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pytest', '0015_alphabet_word'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alphabet',
            table='Alphabet',
        ),
    ]
