# Generated by Django 5.1.3 on 2025-02-21 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pytest', '0016_alter_alphabet_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alphabet',
            table='pytest.Alphabet',
        ),
    ]
