# Generated by Django 5.1.3 on 2025-02-21 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pytest', '0018_alter_alphabet_table_alter_word_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alphabet',
            table='Alphabet',
        ),
        migrations.AlterModelTable(
            name='word',
            table='Word',
        ),
    ]
