# Generated by Django 5.1.3 on 2025-02-21 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pytest', '0019_alter_alphabet_table_alter_word_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['word']},
        ),
    ]
