# Generated by Django 5.1.3 on 2025-02-25 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pytest', '0022_remove_user_age_remove_user_gender_remove_user_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
