# Generated by Django 5.1.3 on 2025-02-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pytest', '0023_remove_profile_email_remove_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, default='Unknown', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
